[package]
name = "tl"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
chrono = "0.4"
dialoguer = "0.11"
dirs = "6"
rusqlite = { version = "0.32", features = ["bundled"] }
prost = "0.13"

[build-dependencies]
prost-build = "0.13"
